
import numpy as np
import matplotlib.pyplot as plt

import compute_ground_truth_model_solution
import compute_apriori_model_solution_reversedtime
import  compute_adjoint_solution
import compute_kernels